format = """
[](#45475A)\
$username\
[](bg:#769ff0 fg:#45475A)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_commit\
$git_status\
[](fg:#394260 bg:#45475A)\
$c\
$gradle\
$java\
$nodejs\
$python\
$rust\
$php\
[](fg:#45475A bg:#1D2230)\
$time\
[](fg:#1D2230)\
\n$character"""

[username]
show_always = true
style_user = "fg:#BAC2DE bg:#45475A"
style_root = "fg:#BAC2DE bg:#45475A"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "fg:#1D2230 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"videos" = " "
"templates" = " "

[c]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
commit_hash_length = 7
style = "bg:#394260"
format = '[[ $hash$tag ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind)](fg:#769ff0 bg:#394260)]($style)'

[gradle]
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#45475A"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#45475A)]($style)'

[python]
symbol = " "
style = "bg:#45475A"
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "bg:#45475A"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#45475A)]($style)'

[golang]
symbol = ""
style = "bg:#45475A"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#45475A)]($style)'

[php]
symbol = ""
style = "bg:#45475A"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#45475A)]($style)'

[time]
disabled = false
time_format = "%R"  # Hour:Minute Format
style = "bg:#1D2230"
format = '[[  $time ](fg:#BAC2DE bg:#1D2230)]($style)'
