#!/bin/bash
#  _                                          
# | |__  ___ _ ____      ___ __ ___  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           |_|                               
#
# Main configs
bspc monitor -d 1 2 3 4 5 6

bspc config border_width            3
bspc config window_gap              15
bspc config split_ratio             0.5

bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   false

bspc config focused_border_color    "#a6e3a1"
bspc config normal_border_color     "#89b4fa"

# Window rules
bspc config external_rules_command ~/.config/bspwm/rules

# Set specific desktops as monocle
cur_desktop=$(bspc query -D -d focused --names)
bspc desktop "^1" -l monocle
bspc desktop "^5" -l monocle
bspc desktop "^6" -l monocle
bspc desktop -f "$cur_desktop"

#              _            _             _
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|
#
# Xsetroot
xsetroot -cursor_name left_ptr

# Feh (wallpaper setter)
feh --bg-fill "$(cat ~/.config/feh/bspwm-wallpaper.txt)"

# Xset
xset s 0
xset +dpms dpms 0 0 0

# Sxhkd
pidof -q sxhkd || sxhkd &

# Picom (compositor)
pidof -q picom || picom &

# Polybar (taskbar)
bspwm-launch-polybar.sh

# Xidlehook, i3lock-color (locker)
bspwm-launch-xidlehook.sh

# Dunst (notification manager)
pidof -q dunst || dunst &

# Polkit-gnome (polkit)
pidof -q polkit-gnome-authentication-agent-1 || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Nm-applet (network)
pidof -q nm-applet || nm-applet &

# Clipcatd (clipboard manager)
pidof -q clipcatd || clipcatd
