#!/bin/bash
#  _                                          
# | |__  ___ _ ____      ___ __ ___  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           |_|                               
#
## Main configs
bspc monitor -d " 󰈹 " "  " " 󰭹 " " 󰓓 " " 󰋋 " "  "

bspc config border_width            3
bspc config window_gap              15

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   false

bspc config focused_border_color    "#a6e3a1"
bspc config normal_border_color     "#89b4fa"


## Window rules

# 1
bspc rule -a firefox          follow=on     desktop="^1"  state=tiled
bspc rule -a Brave-browser    follow=on     desktop="^1"  state=tiled

# 2
bspc rule -a kitty            follow=on
bspc rule -a kitty:*:xcolor   hidden=on
bspc rule -a Alacritty        follow=on
bspc rule -a dragon           follow=on     state=floating
bspc rule -a mpv              follow=on

# 3
bspc rule -a discord          desktop="^3"  state=tiled

# 4
bspc rule -a steam            desktop="^4"  state=tiled
bspc rule -a Lutris           desktop="^4"  state=tiled                            

# 5
bspc rule -a Spotify                desktop="^5" state=tiled

# 6
bspc rule -a plasma-systemmonitor   desktop="^6" state=tiled


## Set layouts

# Get current desktop
cur_desktop=$(bspc query -D -d focused --names)

# Set specific desktops as monocle
bspc desktop "^1" -l monocle
bspc desktop "^5" -l monocle
bspc desktop "^6" -l monocle

# Return to current desktop
bspc desktop -f "$cur_desktop"


## Autostart

# Set cursor
xsetroot -cursor_name left_ptr

# Launch feh (wallpaper setter)
feh --bg-fill "$(cat ~/.config/feh/bspwm-wallpaper.txt)"

# Launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Xset
xset s 0
xset +dpms dpms 0 0 0

# Launch xidlehook and i3lock-color (locker)
bspwm-launch-xidlehook.sh

# Launch picom (compositor)
killall -q picom
picom &

# Launch polybar (taskbar)
bspwm-launch-polybar.sh

# Launch dunst (notification manager)
killall -q dunst
dunst & 

# Launch polkit-gnome (polkit)
killall -q polkit-gnome-authentication-agent-1
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Launch nm-applet
killall -q nm-applet
nm-applet &

# Launch clipcatd (clipboard manager)
clipcatd --replace
